CREATE TABLE role(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    descn VARCHAR(200)
);

CREATE TABLE `user`(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    PASSWORD VARCHAR(50),
    STATUS INTEGER,
    descn VARCHAR(200)
);

CREATE TABLE user_role(
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT
);